### ISSUE TITLE
Hi LuckFire

### ISSUE THREAD

**Issue by ghost** [LuckFire/midnight-mars#1]
from your beste friendo

**Comment by LuckFire** [comment]
hello pavy owo

**Comment by ghost** [comment]
can i help with midnight mars pllleeeaaaasseeeeee

**Comment by LuckFire** [comment]
witwot toho

**Comment by ghost** [comment]
uhh....anything!

**Comment by ghost** [comment]
pls pls

**Comment by DanKGooGLy** [comment]
![image](https://user-images.githubusercontent.com/34890978/114960273-b3fb2200-9e34-11eb-93d5-8e60e8d5e839.png)
Midnight on mars looks like this dumbass

**Comment by LuckFire** [comment]
yo thats cool and all but i dont care

**Comment by ghost** [comment]
poof

**Comment by LuckFire** [comment]
ppPoof
