### ISSUE TITLE
Issues with the theme

### ISSUE THREAD

**Issue by gayclown** [LuckFire/Midnight-Mars#1]
**Text Popout looks a bit off.** (either change the placement of the account panel or just make it like the default one, that also fixes the spotify addon issue.)
https://imgur.com/a/MWZ0QsG

**also no Spotify overlay/player available :(**

**Comment by LuckFire** [comment]
ill take a look at it tmrw, for now you can just disable that addon

also, can you go into more detail of what you mean by “also no Spotify overlay/player available”?

**Comment by gayclown** [comment]
my bad, the spotify plugin was just acting up, it got fixed

**Comment by gayclown** [comment]
i was talking about this btw https://imgur.com/a/Af0DPHj

**Comment by LuckFire** [comment]
alrighty, probably was some css snippet that did that because this theme doesn't really mess with the bar.

also ty for pointing z-indexing issue out, just fixed it so run git pull to update :>
