### ISSUE TITLE
The theme no longer works properly

### ISSUE THREAD

**Issue by mrcorpz** [LuckFire/midnight-mars#11]
I noticed that the theme no longer works properly on latest discord canary.

![image](https://user-images.githubusercontent.com/79889814/148631578-eec224ce-11d1-4cbf-8f7e-812f2cd51db4.png)

**Comment by InfernoEye** [comment]
Agree, it doesn't work anymore, like all of em.

**Comment by LuckFire** [comment]
aware of this, v3 will probably be ready sometime soon ~~i say that as im just starting to work on it~~
pls be patient, it'll be functional again soon!!

**Comment by mrcorpz** [comment]
Soon™

**Comment by ghost** [comment]
Soon™™

**Comment by RoseyLemonz** [comment]
Soon™™™

**Comment by InfernoEye** [comment]
Soon™™™™

**Comment by LuckFire** [comment]
I will no longer be maintaining this theme. Please read the README for more information.
