### ISSUE TITLE
Weird small ring in profile picture?

### ISSUE THREAD

**Issue by MultipedBeatle** [LuckFire/midnight-mars#3]
Hi there, I just started using this theme and noticed that there is a weird ring overlaid on top of the profile pictures. My enabled plugins are Activity Backgrounds, Better Emoji Tooltips, Better Replies, Better Status Indicators. brainfuck, Clickable Message Edits, Cake Day, DM Typing Indicator, emojifier, Emote Utility, Hot remount, Image to Clipboard, LMGTFY, MCInfo, Mock, Online Friends Count, Open in Spotify, Plugin Downloader, Privacy Tab, Quick Mute Channel, Scream, Smooth Scroll, Theme Downloader, Theme Toggler, VCTimer, Voice chat utilities, Voice User Count, Wekbook Tags, Who Reacted, and XSOverlay Discord Notifications. I know a lot of those probably would not change or cause this, but I feel like a full list is better than no list at all. I also have the Discolored and Modern Channel Indicators themes activated along side MidnightMars. This could not be a problem with the theme at all, but I only noticed this issue after switching to this theme. Thank you so much and sorry for the long list!

![eg1](https://user-images.githubusercontent.com/55055851/116018237-3ccd4700-a607-11eb-8000-a2ae31639140.PNG)
![eg2](https://user-images.githubusercontent.com/55055851/116018242-3f2fa100-a607-11eb-8aaa-db388d123a62.PNG)

**Comment by MultipedBeatle** [comment]
![eg3](https://user-images.githubusercontent.com/55055851/116171008-8f713680-a6cd-11eb-9e6d-80fb44f22b94.PNG)
This has also started happening, but I have no clue why.

**Comment by LuckFire** [comment]
the ring is cause of Radial Status by Gibbu, which is an addon for this theme
as for the issue: that's because of the statuses everywhere plugin (most likely)
