### ISSUE TITLE
Very high discord usage

### ISSUE THREAD

**Issue by plshelp1** [LuckFire/midnight-mars#4]
First off I want to say that this is by far the best discord theme I have used but, I have an issue where the discord usage is very high while using this theme. With all other themes, I have used my discord usage stays around 2% but when I use the MIDNIGHT MARS theme it spikes up to 9%-10%. please fix this because I want to use this theme very badly but it's just not worth the performance loss.

**Comment by LuckFire** [comment]
if you can give me other themes as reference that use "low" performance, i may be able to do something about it
i really never pay attention to this, so reason im asking for references

**Comment by plshelp1** [comment]
Themes such as Nox, The Great Mountain Site, Black Hole. These are the other themes I have and they all seem to have low usage.

**Comment by LuckFire** [comment]
what mod do you use this on? BD or Powercord (im assuming BD)

**Comment by plshelp1** [comment]
I use this on BD.

**Comment by LuckFire** [comment]
will look into this, i may have a clue of why

**Comment by plshelp1** [comment]
Thank you!

**Comment by LuckFire** [comment]
already found one thing that causes spikes in cpu, however i will need to keep looking as it still continues to happen.
will roll out an update whenever i get it down enough. closing this issue for now.
