### ISSUE TITLE
How to enable buttons

### ISSUE THREAD

**Issue by Daoprotoss** [LuckFire/midnight-mars#6]
Hello, im noob and i need help

The screenshot of the buttons has
![image](https://user-images.githubusercontent.com/61596681/118366831-23397280-b5a9-11eb-959b-f982b3d23ea1.png)

And I only have 1 button :(
![image](https://user-images.githubusercontent.com/61596681/118367024-5bd94c00-b5a9-11eb-9ca8-18781a63244a.png)

**Comment by LuckFire** [comment]
reload your discord or reinstall the theme, either or should fix this.
will look into getting it to use a path instead so this issue wont occur anymore, so i will be closing this issue.
