### ISSUE TITLE
Misc things I've noticed

### ISSUE THREAD

**Issue by ghost** [LuckFire/midnight-mars#9]
Hello! So, love the theme, love the aesthetic, I think it's all super cute! You did a great job on it :)

I did notice a few things that could be improved, though. Most prominently, the Friends Tab. Certain corners aren't rounded, certain ones are, line thickness and depth are all over the place. I think it would benefit from a small touch-up.
Here's my mockup to show what I mean;
![hehehe](https://user-images.githubusercontent.com/73834086/129145069-0b4fdb03-d746-4eb0-ab56-79e0ec04090d.png)
I tried to keep everything equal as best I could, but hopefully it gets the intent across lol

Besides Friends, Discovery is a bit of a mess since it was added after release, and as such is a completely untouched page, except for the basic colors and all that. But honestly, given how kinda useless the tab is, I totally get not wanting to touch it.
Another small detail I noticed is that in DMs, one side of the tab is rounded, while the other is not. Here;
![friends dm](https://user-images.githubusercontent.com/73834086/129145879-53127343-c54b-4bef-bd4b-5f5bd79a0e1f.png)
I assume the intent was to have them be smooth, but do with that what you will.

Anyway! Yeah. Not much else I can tell that's wrong, per-say. But hopefully this was helpful! Again, love what you did with this and I respect the hell out of the hard work. Best wishes and all that with whatever projects u do! :)

**Comment by LuckFire** [comment]
i'm currently rewriting the theme (no eta on when it's done)

ill take this feedback into consideration, thank you very much! (will leave this issue open til the rewrite is out)
